### ISSUE TITLE
"Account" page blank, errors fill console

### ISSUE THREAD

**Issue by alectrocute** [stripe/stripe-billing-typographic#12] opened 2018-10-08 22:24 UTC
![ss](https://alec.wtf/squaretype.png)

Console log:

```
q.stripe.com/:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
15:21:50.088 q.stripe.com/:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
15:21:54.661 vue.runtime.esm.js:587 [Vue warn]: Property or method "store" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Account> at /var/www/pi/client/src/components/Account.vue
       <Typographic> at /var/www/pi/client/src/components/Typographic.vue
         <Root>
Re @ vue.runtime.esm.js:587
15:21:54.661 vue.runtime.esm.js:587 [Vue warn]: Error in render: "TypeError: Cannot read property 'email' of undefined"

found in

---> <Account> at /var/www/pi/client/src/components/Account.vue
       <Typographic> at /var/www/pi/client/src/components/Typographic.vue
         <Root>
Re @ vue.runtime.esm.js:587
15:21:54.661 vue.runtime.esm.js:1737 TypeError: Cannot read property 'email' of undefined
    at Proxy.cc (Payment.vue:4)
    at a.e._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at kn.get (vue.runtime.esm.js:3138)
    at new kn (vue.runtime.esm.js:3127)
    at e (vue.runtime.esm.js:2791)
    at a.ir.$mount (vue.runtime.esm.js:7995)
    at init (vue.runtime.esm.js:4133)
    at vue.runtime.esm.js:5604
    at l (vue.runtime.esm.js:5551)
_t @ vue.runtime.esm.js:1737
15:21:55.842 :3000/#/login:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
15:21:59.875 vue.runtime.esm.js:587 [Vue warn]: Property or method "store" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Account> at /var/www/pi/client/src/components/Account.vue
       <Typographic> at /var/www/pi/client/src/components/Typographic.vue
         <Root>
Re @ vue.runtime.esm.js:587
15:21:59.875 vue.runtime.esm.js:587 [Vue warn]: Error in render: "TypeError: Cannot read property 'email' of undefined"

found in

---> <Account> at /var/www/pi/client/src/components/Account.vue
       <Typographic> at /var/www/pi/client/src/components/Typographic.vue
         <Root>
Re @ vue.runtime.esm.js:587
15:21:59.875 vue.runtime.esm.js:1737 TypeError: Cannot read property 'email' of undefined
    at Proxy.cc (Payment.vue:4)
    at a.e._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at kn.get (vue.runtime.esm.js:3138)
    at new kn (vue.runtime.esm.js:3127)
    at e (vue.runtime.esm.js:2791)
    at a.ir.$mount (vue.runtime.esm.js:7995)
    at init (vue.runtime.esm.js:4133)
    at vue.runtime.esm.js:5604
    at l (vue.runtime.esm.js:5551)
_t @ vue.runtime.esm.js:1737
```

Node version: 8.12.0

**Comment by ctrudeau-stripe** [comment] 2019-08-21 21:26
Can you try the latest version and let me know if this is still happening? Unable to reproduce closing for now. Thank you for reporting.

**Closed by ctrudeau-stripe** 2019-08-21 21:26 UTC
