### ISSUE TITLE
Server error on login

### ISSUE THREAD

**Issue by Jacobh2** [stripe/stripe-billing-typographic#13] opened 2018-10-24 09:03 UTC
Testing to login after I've created an account and signed out, but then I only get an Server Internal Error

To reproduce: Go to sign in page and try:
Username: `john1337@example.com`
Password: `password`

![image](https://user-images.githubusercontent.com/6471372/47419291-2a46ce00-d77c-11e8-811f-7a0fa564a8af.png)

**Comment by Jacobh2** [comment] 2018-12-10 11:31
Ping  @mg-stripe

**Comment by ctrudeau-stripe** [comment] 2019-08-21 18:59
Thank you for the report. Looks like the issue was fixed as I wasn't able to reproduce it. Closing for now, please reopen if it still happens.

**Closed by ctrudeau-stripe** 2019-08-21 18:59 UTC
